apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment 
  labels:
    app: groceryapp
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: groceryapp
  template:
    metadata:
      labels:
        app: groceryapp 
    spec:
      containers:
      - name: grocery-app 
        image: sanniboena/dockerrepo:groceryapp 
        ports:
        - containerPort: 8080 
