apiVersion: v1
kind: Service
metadata:
  name: service 
spec:
  selector:
    app: groceryapp
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: HTTP
    port: 8080 #Service port
    targetPort: 8080 #The port for the React.js application container
