apiVersion: v1
kind: Service
metadata:
  name: service 
spec:
  selector:
    app: groceryapp
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 3000 #Service port
    targetPort: 3000 #The port for the React.js application container
